# Generated by Django 5.1.7 on 2025-04-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On-site', 'On-site')], max_length=50)),
                ('type', models.CharField(choices=[('Full-time', 'Full-time'), ('Contract', 'Contract')], max_length=50)),
                ('salary', models.CharField(choices=[('$60k - $80k', '$60k - $80k'), ('$70k - $90k', '$70k - $90k'), ('$80k - $100k', '$80k - $100k'), ('100k+', '100k+')], max_length=50)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
