# Generated by Django 4.2.17 on 2025-04-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('Remote', 'Remote'), ('Hybrid   ', 'Hybrid'), ('On-site', 'On-site')], max_length=50),
        ),
    ]
