services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    environment:
      - VITE_API_URL=http://backend:5000/api
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - FRONTEND_URL=http://frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
