# Generated by Django 4.2.17 on 2025-04-14 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='additional_info',
            new_name='additionalInfo',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='career_interests',
            new_name='careerInterests',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='company_name',
            new_name='companyName',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='company_role',
            new_name='companyRole',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='company_size',
            new_name='companySize',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='current_job_title',
            new_name='currentJobTitle',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='experience_level',
            new_name='experienceLevel',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='location_preference',
            new_name='locationPreference',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='primary_skills',
            new_name='primarySkills',
        ),
    ]
