# Generated by Django 4.2.17 on 2025-04-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_additional_info_useraccount_additionalinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='agree_to_terms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='ai_matching',
            field=models.BooleanField(default=True),
        ),
    ]
