# Generated by Django 4.2.17 on 2025-04-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_feed_comments_count_feed_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
