# Generated by Django 4.2.17 on 2025-04-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_feed_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='type',
            field=models.CharField(choices=[('media', 'Media'), ('event', 'Event'), ('article', 'Article'), ('live', 'Live'), {'text', 'Text'}], max_length=20),
        ),
    ]
