# Generated by Django 4.2.17 on 2025-04-16 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0004_alter_feed_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='likes',
        ),
        migrations.AlterField(
            model_name='feed',
            name='type',
            field=models.CharField(choices=[('media', 'Media'), ('event', 'Event'), ('article', 'Article'), ('live', 'Live'), ('text', 'Text')], max_length=20),
        ),
        migrations.AddField(
            model_name='feed',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
